### ISSUE TITLE
Ethernet & TCP/IP

### ISSUE THREAD

**Issue by oli-obk** [AdaCore/bareboard#12]
Are there any plans on making use of the Ethernet port on the stm32f7 discovery board?

**Comment by Fabien-Chouteau** [comment]
It's definitely on the TODO list, please tell us if you start working on it.

**Comment by lambourg** [comment]
If you look at the svd branch, there's examples/ethdemo that starts implementing some support for it. You can start from that and add what's missing.

**Comment by lambourg** [comment]
The SVD branch has now been merged in master. So indeed, if you want to contribute, please have a look at components/eth.

This has not been integrated yet with the general framework as it's still a very early stage driver, but that's some basis you can start with.

Best regards,
- Jerome
