### ISSUE TITLE
Driver depends on Board?

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/bareboard#18]
drivers/stm32-sdram.adb depends on boards/stm32f429_discovery.ads: is this right?

**Comment by lambourg** [comment]
As previously stated by Fabien, this branch is now considered obsolete. Most of the work is now performed on the 'svd' branch where STM32.SDRAM is not considered anymore as part of the drivers section, but as part of the board/components

**Comment by simonjwright** [comment]
>As previously stated by Fabien, this branch is now considered obsolete.

Oh. Missed that.

Odd for the _master_ branch to be obsolete.

**Comment by lambourg** [comment]
It's going to be fixed soon ;)

**Comment by Matthias-R** [comment]
Regarding your first question: Yes, I think that's right. It is not really a generic driver for any type of SDRAM connected to the FMC, it's tailored to the SDRAM fitted on the discovery board.
